language: node_js
services:
  - redis-server
node_js:
  - "8.12.0"
before_install:
  - export BLOT_PANDOC_PATH=$(which pandoc)
cache:
  directories:
    - node_modules
env:
  global:
    - CXX=g++-4.8
  matrix:
    - BLOT_TESTS_SEED=26921
    - BLOT_TESTS_SEED=15579
    - BLOT_TESTS_SEED=
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pandoc
      - g++-4.8    